// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqqnzdpwnwdhmnmhtujw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxcW56ZHB3bndkaG1ubWh0dWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTc1MDQsImV4cCI6MjA1OTE5MzUwNH0.qVZSJquj7s5imViEMejWduf_8nlAPCVq345AXXrOLCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);